# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[(3, 'WORSE'), ('1', 'BAD'), (2, 'MODERATE')], max_length=50),
        ),
    ]
