# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20170809_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[('2', 'MODERATE'), ('3', 'WORSE'), ('1', 'BAD')], max_length=50),
        ),
    ]
