# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20170809_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='area',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[('2', 'MODERATE'), ('1', 'BAD'), ('3', 'WORSE')], max_length=50),
        ),
    ]
